// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PegaVisaoApi.Data;

#nullable disable

namespace PegaVisaoApi.Migrations
{
    [DbContext(typeof(PegaVisaoContext))]
    [Migration("20260924150812_AdicionarCheckoutCuponsEPagamentos")]
    partial class AdicionarCheckoutCuponsEPagamentos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PegaVisaoApi.Models.AvaliacaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Nota")
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ProdutoId", "UsuarioId")
                        .IsUnique();

                    b.ToTable("AvaliacoesProdutos", t =>
                        {
                            t.HasCheckConstraint("CK_Avaliacao_Nota", "\"Nota\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.CotacaoFrete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CarrinhoHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CepDestino")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<string>("ConexaoId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ConsumidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OpcoesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Sandbox")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpiraEm");

                    b.ToTable("CotacoesFrete");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Cupom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DescontoMaximo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("Excluido")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("InicioEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LimitePorUsuario")
                        .HasColumnType("integer");

                    b.Property<int?>("LimiteTotal")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("ValidadeEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Cupons", t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_Valores", "\"Valor\" > 0 AND \"ValorMinimo\" >= 0 AND (\"Tipo\" = 'Fixo' OR (\"Tipo\" = 'Percentual' AND \"Valor\" <= 100))");
                        });
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Enderecos");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<int>("VariacaoProdutoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.HasIndex("VariacaoProdutoId");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.MelhorEnvioConexao", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccessTokenProtegido")
                        .HasColumnType("text");

                    b.Property<int?>("AdministradorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NavegadorHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("RefreshTokenProtegido")
                        .HasColumnType("text");

                    b.Property<DateTime?>("StateExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("StateHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.ToTable("MelhorEnvioConexoes", (string)null);
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CheckoutHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("CheckoutSessionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("CupomCodigo")
                        .HasColumnType("text");

                    b.Property<int?>("CupomId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EstadoEstoque")
                        .HasColumnType("integer");

                    b.Property<bool>("ExcluidoPeloCliente")
                        .HasColumnType("boolean");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FreteCotacaoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FretePrazoDias")
                        .HasColumnType("integer");

                    b.Property<bool?>("FreteSandbox")
                        .HasColumnType("boolean");

                    b.Property<string>("FreteServico")
                        .HasColumnType("text");

                    b.Property<int?>("FreteServicoId")
                        .HasColumnType("integer");

                    b.Property<string>("FreteTransportadora")
                        .HasColumnType("text");

                    b.Property<string>("FreteVolumesJson")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoCheckoutUrl")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoOrderId")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoPaymentId")
                        .HasColumnType("text");

                    b.Property<string>("MercadoPagoStatus")
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("PagamentoExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("PagamentoLeaseAte")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PagamentoPayloadJson")
                        .HasColumnType("text");

                    b.Property<string>("PaymentIdempotencyKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PixQrCode")
                        .HasColumnType("text");

                    b.Property<string>("PixQrCodeBase64")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProximaConsultaEstoqueEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorDesconto")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorFrete")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutSessionId")
                        .IsUnique();

                    b.HasIndex("CupomId");

                    b.HasIndex("FreteCotacaoId")
                        .IsUnique();

                    b.HasIndex("PaymentIdempotencyKey")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.HasIndex("EstadoEstoque", "ProximaConsultaEstoqueEm");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AlturaCm")
                        .HasColumnType("numeric");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ComprimentoCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImagemSecundaria")
                        .HasColumnType("text");

                    b.Property<string>("ImagemTerciaria")
                        .HasColumnType("text");

                    b.Property<decimal?>("LarguraCm")
                        .HasColumnType("numeric");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PesoKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Preco")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.TentativaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoErro")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinalizadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("HttpStatus")
                        .HasColumnType("integer");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PedidoId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("TentativasPagamento");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RecuperacaoEnviadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RecuperacaoExpiraEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RecuperacaoHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("VersaoSessao")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.VariacaoProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Estoque")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("EstoqueReservado")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("integer");

                    b.Property<string>("Tamanho")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.ToTable("VariacaoProdutos", t =>
                        {
                            t.HasCheckConstraint("CK_Variacao_Estoque", "\"Estoque\" >= 0 AND \"EstoqueReservado\" >= 0 AND \"EstoqueReservado\" <= \"Estoque\"");
                        });
                });

            modelBuilder.Entity("PegaVisaoApi.Models.AvaliacaoProduto", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PegaVisaoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Endereco", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Usuario", "Usuario")
                        .WithOne("Endereco")
                        .HasForeignKey("PegaVisaoApi.Models.Endereco", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.ItemPedido", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PegaVisaoApi.Models.VariacaoProduto", "VariacaoProduto")
                        .WithMany()
                        .HasForeignKey("VariacaoProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("VariacaoProduto");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Pedido", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Cupom", "Cupom")
                        .WithMany()
                        .HasForeignKey("CupomId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PegaVisaoApi.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cupom");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Produto", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.TentativaPagamento", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.VariacaoProduto", b =>
                {
                    b.HasOne("PegaVisaoApi.Models.Produto", "Produto")
                        .WithMany("Variacoes")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Pedido", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Produto", b =>
                {
                    b.Navigation("Variacoes");
                });

            modelBuilder.Entity("PegaVisaoApi.Models.Usuario", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
